In [2]:
a

[23, 45, 35, 66, 64, 75, 23]

In [6]:
import numpy as np
np.array(a)*3


array([ 69, 135, 105, 198, 192, 225,  69])

In [ ]:
perm = [34,45,56,45,34,23]

In [35]:
l = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]

In [24]:
l

[12,
 34,
 45,
 78,
 0.8,
 0.12,
 0.5651,
 'Permeability',
 'porosity',
 ['second_list', 4334, 2323, ['fgfd']],
 [34, 45, 56, 45, 34, 23]]

In [ ]:
perm = [34,45,56,45,34,23]

In [25]:
li = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]

In [11]:
perm =[45,31,45,67,12,8,241,43]

In [14]:
list = ['then',"free",'you','kite',[67,'saturation','density'],prem]

In [30]:
list

['then', 'free', 'you', 'kite', [67, 'saturation', 'density'], 'prem']

In [28]:
list

['then', 'free', 'you', 'kite', [67, 'saturation', 'density'], 'prem']

In [29]:
perm = [34,45,56,45,34,23]
l = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]


In [17]:
l

[12,
 34,
 45,
 78,
 0.8,
 0.12,
 0.5651,
 'Permeability',
 'porosity',
 ['second_list', 4334, 2323, ['fgfd']],
 [34, 45, 56, 45, 34, 23]]

In [18]:
perm = [34,45,56,45,34,23]

In [ ]:
l = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]


In [19]:
l

[12,
 34,
 45,
 78,
 0.8,
 0.12,
 0.5651,
 'Permeability',
 'porosity',
 ['second_list', 4334, 2323, ['fgfd']],
 [34, 45, 56, 45, 34, 23]]

In [20]:
perm = [34,45,56,45,34,23]

In [21]:
l = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]


In [22]:
l

[12,
 34,
 45,
 78,
 0.8,
 0.12,
 0.5651,
 'Permeability',
 'porosity',
 ['second_list', 4334, 2323, ['fgfd']],
 [34, 45, 56, 45, 34, 23]]

In [31]:
perm =[45,31,45,67,12,8,241,43]

In [36]:
list = ['then',"free",'you','kite',[67,'saturation','density'],perm]

In [76]:
list

['then',
 'free',
 'you',
 'kite',
 [67, 'saturation', 'density'],
 [45, 31, 45, 67, 12, 8, 241, 43]]

In [38]:
perm = [34,45,56,45,34,23]

In [39]:
l = [12,34,45,78,0.8,0.12,0.5651,'Permeability','porosity',['second_list',4334,2323,['fgfd']],perm]

In [40]:
l

[12,
 34,
 45,
 78,
 0.8,
 0.12,
 0.5651,
 'Permeability',
 'porosity',
 ['second_list', 4334, 2323, ['fgfd']],
 [34, 45, 56, 45, 34, 23]]

In [41]:
l[-1:-3:-3]

[[34, 45, 56, 45, 34, 23]]

In [42]:
l[-1][1:4:2]

[45, 45]

In [44]:
l[-1][-3::-2]

[45, 45]

# append: adds value at the end of list
# empty lists are used to populate it in later stage?

In [45]:
crude_density = []

In [46]:
crude_density.append(43)

In [47]:
crude_density

[43]

In [48]:
crude_density.extend([54,43])

In [49]:
crude_density

[43, 54, 43]

In [50]:
crude_density.append([54,43])

In [51]:
crude_density

[43, 54, 43, [54, 43]]

#insert: like append, inserting item at a particular index

In [52]:
a = [23,34,32,54,32,45]

In [53]:
a

[23, 34, 32, 54, 32, 45]

In [54]:
a.insert(4,"Petroleum")

In [55]:
a

[23, 34, 32, 54, 'Petroleum', 32, 45]

# List Operations

In [57]:
a = [13,23,33]
b = [53,63,73]

In [58]:
a+b

[13, 23, 33, 53, 63, 73]

In [59]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [60]:
a*3

[13, 23, 33, 13, 23, 33, 13, 23, 33]

In [61]:
b*5

[53, 63, 73, 53, 63, 73, 53, 63, 73, 53, 63, 73, 53, 63, 73]

In [62]:
a.pop(2)

33

In [63]:
a

[13, 23]

In [65]:
import numpy as np

In [66]:
a

[13, 23]

In [21]:
np.array(a)*2

array([26, 46])

# Range

In [68]:
range(15)

range(0, 15)

In [70]:
list(range(15))

TypeError: 'list' object is not callable

In [71]:
list

['then',
 'free',
 'you',
 'kite',
 [67, 'saturation', 'density'],
 [45, 31, 45, 67, 12, 8, 241, 43]]

In [72]:
range(10)

range(0, 10)

In [80]:
list(range(10))

TypeError: 'list' object is not callable

In [74]:
range(6)

range(0, 6)

In [86]:
list(range(6))

TypeError: 'list' object is not callable

In [81]:
list(range(3,10,2))

TypeError: 'list' object is not callable

In [83]:
list(range(2,101,-1))

TypeError: 'list' object is not callable

In [84]:
# Take inputs from user: start,stop, step
# output list

In [1]:
start = int(input('Enter starting point: '))
stop = int(input('Enter stop point: '))
step = int(input('Enter step size: '))

list(range(start,stop,step))

Enter starting point: 67
Enter stop point: 45
Enter step size: 73


[]

In [2]:
perm =[34,45,56,45,34,23]

In [3]:
l=[45,67,5324,67,568,423,566,52,86,'permeability','porosity','saturation',['second_list',6876878,677898,['dvkujhg']],perm]

In [4]:
l

[45,
 67,
 5324,
 67,
 568,
 423,
 566,
 52,
 86,
 'permeability',
 'porosity',
 'saturation',
 ['second_list', 6876878, 677898, ['dvkujhg']],
 [34, 45, 56, 45, 34, 23]]

In [5]:
l[-1][1::2]

[45, 45, 23]

In [6]:
l[-1][1:-2]

[45, 56, 45]

In [7]:
l[-1][1][2]

TypeError: 'int' object is not subscriptable

In [9]:
l[-1][-3][2]

TypeError: 'int' object is not subscriptable

In [10]:
l[-1][1::4]

[45, 23]

In [11]:
l[-1][1:2:4]

[45]

In [12]:
l[-1][1:4:2]

[45, 45]

In [15]:
l[-1][-3:-6:-2]

[45, 45]

In [17]:
a=[13,23]

In [18]:
a*3

[13, 23, 13, 23, 13, 23]

In [19]:
import numpy as np

In [20]:
np.array(a)*2

array([26, 46])

In [22]:
#range

In [23]:
range(10)

range(0, 10)

In [24]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
list(range(3,10,2))

[3, 5, 7, 9]

In [27]:
list(range(3,9,2))

[3, 5, 7]

In [28]:
list(range(3,11,2))

[3, 5, 7, 9]

In [29]:
list(range(20,0,-1))

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [30]:
list(range(0,100))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [32]:
list(range(1,100))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [33]:
list(range(1,101))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [34]:
list(range(1,101,2))

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [36]:
list(range(2,102,2))

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [37]:
list(range(2,101,2))

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [38]:
list(range(0,100))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [40]:
list(range(0,101))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [41]:
#take inputs for the user: start,stop,step
#output list

In [ ]:
start = ("Enter the starting point : ")
stop = ("Enter the stoping point : ")
step ("Enter the step size : ")

In [ ]:
start = input("Enter the starting point : ")
stop = input("Enter the stoping point : ")
step input("Enter the step size : ")

In [ ]:
start = input("Enter the starting point : ")
stop = input("Enter the stoping point : ")
step = input("Enter the step size : ")

list(range(start,stop,step))

Enter the starting point : 2
Enter the stoping point : 102


In [1]:
a=[1,2,3,4,5]

In [2]:
a

[1, 2, 3, 4, 5]

In [4]:
start = input("Enter the starting point : ")
stop = input("Enter the stoping point : ")
step = input("Enter the step size : ")

list(range(start,stop,step))

Enter the starting point : 2
Enter the stoping point : 102
Enter the step size : 2


TypeError: 'str' object cannot be interpreted as an integer

In [7]:
start = int(input("Enter the starting point : "))
stop = int(input("Enter the stoping point : "))
step = int(input("Enter the step size : "))

list(range(start,stop,step))

Enter the starting point : 2
Enter the stoping point : 102
Enter the step size : 2


[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [8]:
start = int(input('Enter starting point: '))
stop = int(input('Enter stop point: '))
step = int(input('Enter step size: '))

list(range(start,stop,step))

Enter starting point: 67
Enter stop point: 45
Enter step size: 73


[]

# tuples

()

ordered

immutable


In [9]:
oilproduction = (67987,434,4565,3456546)

In [10]:
oilproduction

(67987, 434, 4565, 3456546)

In [12]:
type(oilproduction)

tuple

In [13]:
oilproduction[3]

3456546

In [14]:
## tuple

In [15]:
oilproduction

(67987, 434, 4565, 3456546)

In [18]:
oil_prd = list(oilproduction)

In [19]:
oil_prd

[67987, 434, 4565, 3456546]

In [20]:
oilproduction

(67987, 434, 4565, 3456546)

In [21]:
oilproduction[2] = 65

TypeError: 'tuple' object does not support item assignment

In [22]:
oil_prd[3] = 788

In [23]:
oil_prd

[67987, 434, 4565, 788]

In [24]:
oil_prd[::-1]

[788, 4565, 434, 67987]

In [25]:
oilproduction

(67987, 434, 4565, 3456546)

In [27]:
oilproduction[::-1]

(3456546, 4565, 434, 67987)

In [28]:
oilproduction.reverse()

AttributeError: 'tuple' object has no attribute 'reverse'

In [29]:
oil_prd.reverse()

In [30]:
oil_prd

[788, 4565, 434, 67987]

#### SETS : UNORDERDED DATA STRUCTURES

. {}
. Unique datas
. unordered
. fast than list
. unique elements ,lists

In [31]:
perm = {31,45,657,312,46,256,56,77,23}

In [32]:
perm

{23, 31, 45, 46, 56, 77, 256, 312, 657}

In [33]:
type(perm)

set

In [34]:
perm = {2,2,22,33,344,565,324,1,2,2,33,44,55,565,66,77,77,888,999,999,44,55,6,77,56,565}

In [35]:
perm

{1, 2, 6, 22, 33, 44, 55, 56, 66, 77, 324, 344, 565, 888, 999}

In [36]:
s = {1,1,2,3,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,'ja','ka','ja','ka'}

In [37]:
s

{1, 2, 3, 4, 5, 6, 7, 8, 9, 'ja', 'ka'}

In [38]:
s[3]

TypeError: 'set' object is not subscriptable

In [39]:
s = {"prem","Prem"}

In [40]:
s

{'Prem', 'prem'}

In [41]:
a,A = 56,87

In [42]:
a

56

In [43]:
A

87

In [44]:
length(prem)

NameError: name 'length' is not defined

In [45]:
prem

NameError: name 'prem' is not defined

In [46]:
perm = {31,45,657,312,46,256,56,77,23}

In [47]:
perm

{23, 31, 45, 46, 56, 77, 256, 312, 657}

In [48]:
length(perm)

NameError: name 'length' is not defined

In [49]:
len(perm)

9

In [50]:
len(s)

2